<a href="https://colab.research.google.com/github/sureshcrwr/Mini-Projects/blob/main/Logistic_Simple_Method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Logistic Regression

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

data = pd.read_csv("F:\\GLA\\2019-2020\\ML Projects\\Machine-Learning-master\\Machine-Learning-master\\LogisticRegression\\data\\marks.txt")

# X = feature values, all the columns except the last column
X = data.iloc[:, :-1]

    # y = target values, last column of the data frame
y = data.iloc[:, -1]

X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.2)

model = LogisticRegression()
model.fit(X_train,Y_train)

Y_pred = model.predict(X_test)
    

c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


61    0
4     0
26    0
1     0
64    0
23    1
20    1
93    1
53    0
86    1
60    0
77    0
73    1
11    1
65    1
84    1
38    0
85    0
7     1
13    0
Name: 0, dtype: int64
[0 0 1 1 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1]


In [ ]:
print(Y_pred)

[1 1 1 0 1 1 0 1 0 1 1 1 1 1 1 1 0 1 0 1]


In [ ]:
from sklearn.metrics import confusion_matrix 
cm = confusion_matrix(Y_test, Y_pred) 

print(cm)

[[5 6]
 [0 9]]


In [ ]:
from sklearn.metrics import precision_score, recall_score
pre=precision_score(Y_test, Y_pred)
recall=recall_score(Y_test, Y_pred)

print(pre)
print(recall)

0.6
1.0


# MultiClass Logistic Regression

In [ ]:
from sklearn import datasets
import numpy as np
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
np.set_printoptions(precision=3)
iris = datasets.load_iris()
X = iris.data
y = iris.target

train_x, test_x, train_y, test_y = train_test_split(X, y, test_size=1, random_state=None)

model = LogisticRegression(solver='lbfgs')
model.fit(X,y)

y_pred = model.predict([[6.3,3.3,6.0,2.5]])

print(y_pred)

[2]


c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
